# --- Prepare SaTScan Input Files Script ---

import pandas as pd
import geopandas as gpd
import os
import numpy as np

# --- Configuration ---
script_dir = os.path.dirname(os.path.abspath(__file__))
print(f"Script directory: {script_dir}")

# Define input/output folders based on script directory
INPUT_DATA_DIR = os.path.join(script_dir, "downloaded_data_2019")
POPULATION_CSV = os.path.join(INPUT_DATA_DIR, "population_subzone_processed.csv")
# Use the geojson in the same folder as the script
BOUNDARY_GEOJSON = os.path.join(script_dir, "subzone_boundaries.geojson")

# Use the dengue points gpkg from the subfolder, generated by an older version of download_historical_data_2019.ipynb
# It now generates dengue_points_2019-05-01_to_2019-07-31.shp, because again, geopackage generated by Geopandas doesn't seem to work well with Arcpy for whatever reason
DENGUE_POINTS_GPKG = os.path.join(INPUT_DATA_DIR, f"dengue_points_2019-05-01_to_2019-07-31.gpkg")

SATSCAN_OUTPUT_DIR = os.path.join(script_dir, "satscan_inputs_2019")
os.makedirs(SATSCAN_OUTPUT_DIR, exist_ok=True)
SATSCAN_CASES_FILE = os.path.join(SATSCAN_OUTPUT_DIR, "satscan_cases_final.csv")
SATSCAN_POP_FILE = os.path.join(SATSCAN_OUTPUT_DIR, "satscan_population_final.csv")
SATSCAN_COORD_FILE = os.path.join(SATSCAN_OUTPUT_DIR, "satscan_coordinates_final.csv")

# Define Shapefile output path
CLEANED_BOUNDARY_SHP = os.path.join(SATSCAN_OUTPUT_DIR, "subzone_boundaries_svy21_standardized.shp")

ANALYSIS_YEAR = 2019
MIN_POPULATION = 1

# --- MANUAL NAME MAPPING DICTIONARY ---
name_mapping = {
    "MANDAI ESTATE": "MANDAI EAST",
    "YIO CHU KANG": "YIO CHU KANG EAST",
    "TIONG BAHRU STATION": "TIONG BAHRU",
}
name_mapping = {k.upper().strip(): v.upper().strip() for k, v in name_mapping.items()}
print(f"Applying {len(name_mapping)} manual name mappings.")

# --- Main Processing ---

try:
    # --- 1. Process Subzone Boundaries (Get Definitive List of IDs) ---
    print(f"Processing boundary GeoJSON: {BOUNDARY_GEOJSON}...")
    try:
        if not os.path.exists(BOUNDARY_GEOJSON):
             raise FileNotFoundError(f"Boundary file not found at {BOUNDARY_GEOJSON}")
        
        boundaries_gdf = gpd.read_file(BOUNDARY_GEOJSON)
        subzone_name_field_geojson = 'SUBZONE_NAME'
        if subzone_name_field_geojson not in boundaries_gdf.columns:
            raise ValueError(f"Expected field '{subzone_name_field_geojson}' not found.")

        boundaries_clean = boundaries_gdf[[subzone_name_field_geojson, 'geometry']].copy()
        boundaries_clean.rename(columns={subzone_name_field_geojson: 'Subzone_Name'}, inplace=True)
        boundaries_clean['Location_ID'] = boundaries_clean['Subzone_Name'].astype(str).str.strip().str.upper()

        boundaries_std = boundaries_clean[['Location_ID', 'geometry']].copy()
        boundaries_std.drop_duplicates(subset=['Location_ID'], inplace=True)

        boundaries_svy21 = boundaries_std.to_crs("EPSG:3414")
        print("Boundary GeoJSON processed, standardized, and projected.")
        
        # Save as Shapefile
        # The Shapefile driver will automatically truncate 'Location_ID' to 'Location_I'
        print(f"Warning: Saving to Shapefile. 'Location_ID' field will be truncated to 'Location_I'.")
        boundaries_svy21.to_file(CLEANED_BOUNDARY_SHP, driver="ESRI Shapefile")
        print(f"Standardized boundaries saved to {CLEANED_BOUNDARY_SHP}")

        # The rest of the script still uses the in-memory 'boundaries_svy21' DataFrame
        # which has the *full* 'Location_ID' field, so SaTScan files will be correct.
        all_valid_location_ids_df = pd.DataFrame({'Location_ID': boundaries_svy21['Location_ID'].unique()})
        print(f"Found {len(all_valid_location_ids_df)} unique standardized Location IDs in boundary file.")

    except Exception as e:
        print(f"ERROR processing boundary GeoJSON: {e}")
        exit()

    # --- 2. Generate Cases File (Filter by Valid IDs) ---
    print(f"\nProcessing dengue points: {DENGUE_POINTS_GPKG}...")
    try:
        if not os.path.exists(DENGUE_POINTS_GPKG):
             raise FileNotFoundError(f"Dengue points file not found at {DENGUE_POINTS_GPKG}")
        dengue_points_gdf = gpd.read_file(DENGUE_POINTS_GPKG) # Already in SVY21
        if dengue_points_gdf.crs != boundaries_svy21.crs:
             dengue_points_gdf = dengue_points_gdf.to_crs(boundaries_svy21.crs)

        print("Performing spatial join...")
        joined_gdf = gpd.sjoin(dengue_points_gdf, boundaries_svy21, how="inner", predicate="within")

        if joined_gdf.empty:
             print("Warning: Spatial join resulted in zero matches.")
             satscan_cases = pd.DataFrame(columns=['Location_ID', 'Cases', 'Date'])
        else:
            print(f"Spatial join successful, {len(joined_gdf)} points assigned.")
            satscan_cases = pd.DataFrame()
            satscan_cases['Location_ID'] = joined_gdf['Location_ID'] # Standardized from boundary
            satscan_cases['Cases'] = 1
            satscan_cases['Date'] = pd.to_datetime(joined_gdf['date']).dt.strftime('%Y/%m/%d')

            initial_case_count = len(satscan_cases)
            satscan_cases = satscan_cases[satscan_cases['Location_ID'].isin(all_valid_location_ids_df['Location_ID'])]
            filtered_case_count = len(satscan_cases)
            if initial_case_count != filtered_case_count:
                print(f"Filtered out {initial_case_count - filtered_case_count} case records with invalid Location IDs.")

        satscan_cases.to_csv(SATSCAN_CASES_FILE, index=False)
        print(f"SaTScan cases file saved to {SATSCAN_CASES_FILE}")

    except Exception as e:
        print(f"ERROR processing dengue points or creating cases file: {e}")
        # Allow to continue

    # --- 3. Generate Population File (Merge with ALL Valid IDs) ---
    print(f"\nProcessing population data and merging with all valid locations: {POPULATION_CSV}...")
    try:
        if not os.path.exists(POPULATION_CSV):
             raise FileNotFoundError(f"Population file not found at {POPULATION_CSV}")
        pop_df_raw = pd.read_csv(POPULATION_CSV) 

        pop_df_raw['Location_ID_Std'] = pop_df_raw['Subzone_Name'].astype(str).str.strip().str.upper()
        pop_df_raw['Location_ID_Mapped'] = pop_df_raw['Location_ID_Std'].map(name_mapping).fillna(pop_df_raw['Location_ID_Std'])
        pop_mapped = pop_df_raw[['Location_ID_Mapped', 'Population_2020']].copy()
        pop_mapped.rename(columns={'Location_ID_Mapped': 'Location_ID'}, inplace=True)
        pop_mapped['Population_2020'] = pd.to_numeric(pop_mapped['Population_2020'], errors='coerce')

        satscan_pop = pd.merge(all_valid_location_ids_df, pop_mapped, on='Location_ID', how='left')

        initial_na_count = satscan_pop['Population_2020'].isna().sum()
        if initial_na_count > 0:
            print(f"Found {initial_na_count} valid locations missing population data. Filling with 0 for now.")
            satscan_pop['Population_2020'].fillna(0, inplace=True)

        satscan_pop['Population_2020'] = satscan_pop['Population_2020'].astype(int)

        zero_pop_count = (satscan_pop['Population_2020'] <= 0).sum()
        if zero_pop_count > 0:
            print(f"Found {zero_pop_count} subzones with population 0 (including initially missing). Replacing with {MIN_POPULATION}.")
            satscan_pop['Population_2020'] = np.where(satscan_pop['Population_2020'] <= 0, MIN_POPULATION, satscan_pop['Population_2020'])
            zero_pop_after = (satscan_pop['Population_2020'] <= 0).sum()
            print(f"Population after replacement: Min={satscan_pop['Population_2020'].min()}, Zeros={zero_pop_after}")

        satscan_pop['Year'] = ANALYSIS_YEAR
        satscan_pop.rename(columns={'Population_2020': 'Population'}, inplace=True)
        satscan_pop = satscan_pop[['Location_ID', 'Year', 'Population']]
        satscan_pop.drop_duplicates(subset=['Location_ID', 'Year'], inplace=True)

        satscan_pop.to_csv(SATSCAN_POP_FILE, index=False)
        print(f"SaTScan population file saved to {SATSCAN_POP_FILE}")
        print(f"Final population file has {len(satscan_pop)} rows.")

    except Exception as e:
        print(f"ERROR processing population data or creating population file: {e}")
        exit()

    # --- 4. Generate Coordinates File (Using only valid IDs) ---
    print("\nCalculating centroids and generating coordinates file...")
    try:
        centroids_svy21 = boundaries_svy21.copy()
        centroids_svy21['geometry'] = centroids_svy21.geometry.centroid
        centroids_wgs84 = centroids_svy21.to_crs("EPSG:4326")

        satscan_coords = pd.DataFrame()
        satscan_coords['Location_ID'] = centroids_wgs84['Location_ID'] # Use full, non-truncated name
        satscan_coords['Latitude'] = centroids_wgs84.geometry.y
        satscan_coords['Longitude'] = centroids_wgs84.geometry.x

        satscan_coords.to_csv(SATSCAN_COORD_FILE, index=False)
        print(f"SaTScan coordinates file saved to {SATSCAN_COORD_FILE}")
        print(f"Final coordinates file has {len(satscan_coords)} rows.")

    except Exception as e:
        print(f"ERROR calculating centroids or creating coordinates file: {e}")
        exit()

    print(f"\n--- SaTScan Input File Preparation Complete ---")
    print(f"Files saved in: {SATSCAN_OUTPUT_DIR}")

except FileNotFoundError as e:
    print(f"\nERROR: Input file not found: {e}.")
except Exception as e:
    print(f"\nAn unexpected error occurred: {e}")